study(title="Auto Fib Retracement", shorttitle="Auto Fib Retracement", overlay=true)

fiblength=input(265)
maxr = highest(close, fiblength)
minr = lowest(close, fiblength)
ranr = maxr - minr

ON=plot( maxr , color=black,  title="1")
SS=plot( maxr - 0.236 * ranr, title="0.764", color=#3399FF )
SO=plot( maxr - 0.382 * ranr, title="0.618", color=blue )
FI=plot( maxr - 0.50 * ranr, title="0.5", color=lime )
TE=plot( minr + 0.382 * ranr, title="0.382", color=green )
TT=plot( minr + 0.236 * ranr, title="0.236", color=red )
ZZ=plot( minr , title="0", color=black )

fill(ON,SS, color=red)
fill(SS,SO, color=#3399FF)
fill(SO,FI, color=lime)
fill(FI,TE, color=lime)
fill(TE,TT, color=#3399FF)
fill(TT,ZZ, color=red)